services:
  shiroi-nginx:
    image: nginx:alpine
    container_name: shiroi-nginx
    ports:
      - '12333:80'
    volumes:
      - $HOME/shiroi/deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $HOME/shiroi/deploy/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf:ro
    depends_on:
      - shiroi-app-blue
      - shiroi-app-green
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/nginx-health']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  shiroi-app-blue:
    image: ${SHIROI_IMAGE:-shiroi:latest}
    container_name: shiroi-app-blue
    environment:
      - NODE_ENV=production
    env_file:
      - ${HOME}/shiroi/.env
    volumes:
      - ${HOME}/shiroi/data:/app/data
      - ${HOME}/shiroi/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'sh', '-c', 'curl -f http://$(hostname):2323']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 500m
        reservations:
          memory: 256m

  shiroi-app-green:
    image: ${SHIROI_IMAGE:-shiroi:latest}
    container_name: shiroi-app-green
    environment:
      - NODE_ENV=production
    env_file:
      - ${HOME}/shiroi/.env
    volumes:
      - ${HOME}/shiroi/data:/app/data
      - ${HOME}/shiroi/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'sh', '-c', 'curl -f http://$(hostname):2323']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 500m
        reservations:
          memory: 256m
    # Remove profiles to allow both containers to run simultaneously
    # profiles:
    #   - green

networks:
  default:
    name: shiroi-network
